id: 1b461a8fb59843bfbc0523fa5c383a6e
title: Toh_249-The_Sutra_Teaching_the_Four_Factors-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-007
  eft-text-version: 1.5.2 2019
